### ISSUE TITLE
Possible to apply selectively to gameobjects/sprites?

### ISSUE THREAD

**Issue by majman** [keijiro/KinoFeedback#1]
Amazing effect! Was trying this to create a "ghost trail" type of effect for a single game object rather than the camera, something like sonic the hedgehog:
![sonic](http://i.stack.imgur.com/CCYOb.png)

**Comment by keijiro** [comment]
I think the frame buffer feedback technique doesn't fit this case. It requires a fair amount of video memory and GPU load. This kind of trail effect can be implemented without spending such an amount of resources.
