### ISSUE TITLE
Seems that this is not working on Unity 2020.1 URP

### ISSUE THREAD

**Issue by barisbarisbarisbaris** [keijiro/KinoFeedback#3]
Am I missing out something?
I assign a solid color with 0 alpha. 

Or is this script not compatible to the newest version of Unity?

**Comment by keijiro** [comment]
In general, image effects are not compatible with SRPs (URP/HDRP).

> Or is this script not compatible to the newest version of Unity?

I'm pretty sure that it works on the latest version of Unity with the legacy render pipeline.
